-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 09:45:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Countries` (
  `idCountries` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCountries`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `idLocation` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Country` INT NOT NULL,
  `GPS` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocation`),
  INDEX `country_idx` (`Country` ASC) VISIBLE,
  CONSTRAINT `country`
    FOREIGN KEY (`Country`)
    REFERENCES `mydb`.`Countries` (`idCountries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `location` INT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `location_idx` (`location` ASC) VISIBLE,
  CONSTRAINT `location`
    FOREIGN KEY (`location`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Club` (
  `idClub` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL,
  `Location` INT NOT NULL,
  `CreatedBy` INT NOT NULL,
  `Master` INT NOT NULL,
  `StartDateTime` DATETIME NOT NULL,
  `EndDateTime` DATETIME NULL,
  PRIMARY KEY (`idClub`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `user_idx` (`CreatedBy` ASC, `Master` ASC) VISIBLE,
  INDEX `location_idx` (`Location` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`CreatedBy` , `Master`)
    REFERENCES `mydb`.`User` (`idUser` , `idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location`
    FOREIGN KEY (`Location`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Language` (
  `idLanguage` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLanguage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClubLanguage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ClubLanguage` (
  `Club` INT NOT NULL,
  `Language` INT NOT NULL,
  PRIMARY KEY (`Club`, `Language`),
  INDEX `language_idx` (`Language` ASC) VISIBLE,
  CONSTRAINT `club`
    FOREIGN KEY (`Club`)
    REFERENCES `mydb`.`Club` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `language`
    FOREIGN KEY (`Language`)
    REFERENCES `mydb`.`Language` (`idLanguage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DiveSite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DiveSite` (
  `idDiveSite` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL,
  `Location` INT NOT NULL,
  `StartDateTime` DATETIME NULL,
  `EndDateTime` DATETIME NULL,
  `difficulty` VARCHAR(45) NULL,
  `depthMin` INT NULL,
  `depthMax` INT NULL,
  `compas` TINYINT NULL,
  PRIMARY KEY (`idDiveSite`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `location_idx` (`Location` ASC) VISIBLE,
  CONSTRAINT `location`
    FOREIGN KEY (`Location`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DiveSiteLanguage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DiveSiteLanguage` (
  `diveSite` INT NOT NULL,
  `Language` INT NOT NULL,
  PRIMARY KEY (`diveSite`, `Language`),
  INDEX `language_idx` (`Language` ASC) VISIBLE,
  CONSTRAINT `diveSite`
    FOREIGN KEY (`diveSite`)
    REFERENCES `mydb`.`DiveSite` (`idDiveSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `language`
    FOREIGN KEY (`Language`)
    REFERENCES `mydb`.`Language` (`idLanguage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `user` INT NOT NULL,
  `club` INT NOT NULL,
  INDEX `user_idx` (`user` ASC) VISIBLE,
  INDEX `club_idx` (`club` ASC) VISIBLE,
  PRIMARY KEY (`user`, `club`),
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `club`
    FOREIGN KEY (`club`)
    REFERENCES `mydb`.`Club` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookmarksUserDivesite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookmarksUserDivesite` (
  `User` INT NOT NULL,
  `DiveSite` INT NOT NULL,
  PRIMARY KEY (`User`, `DiveSite`),
  INDEX `diveSite_idx` (`DiveSite` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`User`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `diveSite`
    FOREIGN KEY (`DiveSite`)
    REFERENCES `mydb`.`DiveSite` (`idDiveSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dive` (
  `idDive` INT NOT NULL,
  `diveSite` VARCHAR(45) NULL,
  `boat` VARCHAR(45) NULL,
  `weather` VARCHAR(45) NULL,
  `visibility` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL COMMENT 'weight that the diver has to add to be able to dive.',
  `gear` INT NULL,
  `description` LONGTEXT NULL,
  `Pictures` VARCHAR(45) NULL,
  `location` INT NULL,
  `Tank` VARCHAR(45) NULL,
  `Volume` INT NULL COMMENT 'volume of the tank in L.',
  `pression` DOUBLE NULL,
  `pressionStart` DOUBLE NULL,
  `pressionEnd` DOUBLE NULL,
  `oxygenPercentage` DOUBLE NULL,
  `heliumPercentage` DOUBLE NULL,
  `diveDate` DATE NULL,
  `SAC` DOUBLE NULL,
  `diver` INT NOT NULL,
  `Buddy` INT NULL,
  `startTime` TIME NULL,
  `video` VARCHAR(45) NULL,
  `public` TINYINT NOT NULL,
  PRIMARY KEY (`idDive`),
  INDEX `location_idx` (`location` ASC) VISIBLE,
  INDEX `diver_idx` (`diver` ASC) VISIBLE,
  INDEX `buddy_idx` (`Buddy` ASC) VISIBLE,
  UNIQUE INDEX `video_UNIQUE` (`video` ASC) VISIBLE,
  UNIQUE INDEX `Pictures_UNIQUE` (`Pictures` ASC) VISIBLE,
  CONSTRAINT `location`
    FOREIGN KEY (`location`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `diver`
    FOREIGN KEY (`diver`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `buddy`
    FOREIGN KEY (`Buddy`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certification` (
  `idCertification` INT NOT NULL,
  `user` INT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idCertification`),
  INDEX `user_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `idEvent` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `privacity` TINYINT NOT NULL,
  `club` INT NOT NULL,
  PRIMARY KEY (`idEvent`),
  INDEX `club_idx` (`club` ASC) VISIBLE,
  CONSTRAINT `club`
    FOREIGN KEY (`club`)
    REFERENCES `mydb`.`Club` (`idClub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attend` (
  `Attendees` INT NOT NULL,
  `event` INT NOT NULL,
  PRIMARY KEY (`Attendees`, `event`),
  CONSTRAINT `user`
    FOREIGN KEY (`Attendees`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `event`
    FOREIGN KEY (`Attendees` , `event`)
    REFERENCES `mydb`.`Event` (`idEvent` , `idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Following` (
  `follower` INT NOT NULL,
  `followed` INT NOT NULL,
  PRIMARY KEY (`follower`, `followed`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
